# Generated by Django 3.1.6 on 2021-03-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres_polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_image_url',
            new_name='image_url',
        ),
    ]
