# Generated by Django 3.1.6 on 2021-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres_polls', '0002_auto_20210304_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='album',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='artist',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
